/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('sites').del()
  await knex('sites').insert([
    {
      id: 1,
      latlong: '40.7128,-74.0060',
      address: '12 Barnard St, Wadestown',
      description: 'Community garden in Wadestown',
      councilId: 1,
      userId: '1',
      isPublic: true,
      hasWaterAccess: true,
      isAvailable: true,
      hasShade: false,
      soilType: 'Loamy',
      size: 'Medium',
      accessibility: 'Public transit',
    },
    {
      id: 2,
      latlong: '51.5074,-0.1278',
      address: '456 Park Ln, London',
      description: 'Private garden space near Hyde Park',
      councilId: 2,
      userId: '2',
      isPublic: false,
      hasWaterAccess: true,
      isAvailable: true,
      hasShade: true,
      soilType: 'Sandy',
      size: 'Large',
      accessibility: 'Street parking',
    },
    {
      id: 3,
      latlong: '34.0522,-118.2437',
      address: '789 Vine St, Los Angeles',
      description: 'Rooftop garden in urban LA',
      councilId: 3,
      userId: '3',
      isPublic: true,
      hasWaterAccess: true,
      isAvailable: false,
      hasShade: true,
      soilType: 'Clay',
      size: 'Small',
      accessibility: 'Elevator access',
    },
    {
      id: 4,
      latlong: '48.8566,2.3522',
      address: '1010 Boul Saint-Germain, Paris',
      description: 'Historic garden near Notre Dame',
      councilId: 2,
      userId: '4',
      isPublic: true,
      hasWaterAccess: false,
      isAvailable: true,
      hasShade: true,
      soilType: 'Peaty',
      size: 'Large',
      accessibility: 'Metro and bus',
    },
    {
      id: 5,
      latlong: '-33.8688,151.2093',
      address: '1212 Harbour St, Sydney',
      description: 'Waterfront community space with indigenous plants',
      councilId: 1,
      userId: '5',
      isPublic: true,
      hasWaterAccess: true,
      isAvailable: true,
      hasShade: false,
      soilType: 'Silty',
      size: 'Medium',
      accessibility: 'Ferry and footpath',
    },
    {
      id: 6,
      latlong: '55.7558,37.6173',
      address: '1313 Winter Palace Rd, Moscow',
      description: 'Cold climate garden with greenhouse',
      councilId: 3,
      userId: '6',
      isPublic: false,
      hasWaterAccess: true,
      isAvailable: true,
      hasShade: true,
      soilType: 'Chalky',
      size: 'Medium',
      accessibility: 'Metro and parking',
    },
    {
      id: 7,
      latlong: '35.6895,139.6917',
      address: '1414 Cherry Blossom Ave, Tokyo',
      description: 'Public park with seasonal cherry blossoms',
      councilId: 1,
      userId: '7',
      isPublic: true,
      hasWaterAccess: false,
      isAvailable: true,
      hasShade: true,
      soilType: 'Loamy',
      size: 'Large',
      accessibility: 'Train and bus',
    },
  ])
}
