/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('users').del()
  await knex('users').insert([
    {
      id: 1,
      name: 'John Smith',
      userName: 'jsmith82',
      email: 'john@example.com',
      password: 'password_here',
      location: 'Wellington',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: 'Susan Adams',
      userName: 'sadams77',
      email: 'susan@example.com',
      password: 'password_here',
      location: 'Auckland',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 3,
      name: 'Georgia Brown',
      userName: 'gbrown',
      email: 'georgia@example.com',
      password: 'password_here',
      location: 'Wellington',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 4,
      name: 'Max Turner',
      userName: 'mturner',
      email: 'max@example.com',
      password: 'password_here',
      location: 'Auckland',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 5,
      name: 'Sophie Lee',
      userName: 'slee',
      email: 'sophie@example.com',
      password: 'password_here',
      location: 'Christchurch',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 6,
      name: 'Alice Johnson',
      userName: 'ajohnson',
      email: 'alice@example.com',
      password: 'password_here',
      location: 'Dunedin',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 7,
      name: 'Erik Mattsson',
      userName: 'emattsson',
      email: 'erik@example.com',
      password: 'password_here',
      location: 'Hamilton',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 8,
      name: 'Linda Cartwright',
      userName: 'lcartwright',
      email: 'linda@example.com',
      password: 'hashed_password_here',
      location: 'Napier',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 9,
      name: 'Oscar Wallace',
      userName: 'owallace',
      email: 'oscar@example.com',
      password: 'hashed_password_here',
      location: 'Tauranga',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 10,
      name: 'Rita Patel',
      userName: 'rpatel',
      email: 'rita@example.com',
      password: 'password_here',
      location: 'Palmerston North',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ])
}
